# Generated by Django 2.0.5 on 2018-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdr_report_key', models.BigIntegerField()),
                ('device_problem', models.CharField(max_length=191)),
                ('brand_name', models.TextField(blank=True, null=True)),
                ('manufacturer_name', models.TextField(blank=True, null=True)),
                ('device_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='maude',
            unique_together={('mdr_report_key', 'device_problem')},
        ),
    ]
