# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maude',
            name='brand_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maude',
            name='device_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maude',
            name='manufacturer_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
